module.exports = {
    settings: {
        projectsAmount: Number,
        period: Number,
        startYear: String,
        initial: Boolean
    },
    projects: [ 
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number },
        { code: String, title: String, name: String, scale: Number, unit: String, symbol: String, price: Number }
    ],
    scales: [
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String },
        { year: String, scale: [Number, Number, Number, Number, Number, Number, Number, Number, Number], price: [Number, Number, Number, Number, Number, Number, Number, Number, Number], boundary: String }
    ]
};